### ISSUE TITLE
Example in README does not work

### ISSUE THREAD

**Issue by yimingli** [yutannihilation/gghighlight#11] opened 2018-04-01 21:47 UTC
``` r
library(gghighlight)

d <- purrr::map_dfr(
    letters,
    ~ data.frame(idx = 1:400,
                 value = cumsum(runif(400, -1, 1)),
                 type = .,
                 stringsAsFactors = FALSE))

gghighlight_line(d, aes(idx, value, colour = type), max(value) > 20)
#> Warning: package 'bindrcpp' was built under R version 3.4.4
#> Error in .subset2(x, i): no such index at level 1
```

Created on 2018-04-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.3 (2017-11-30)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/Chicago             
#>  date     2018-04-01
#> Packages -----------------------------------------------------------------
#>  package     * version    date       source                            
#>  assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                    
#>  backports     1.1.2      2017-12-13 CRAN (R 3.4.3)                    
#>  base        * 3.4.3      2017-12-07 local                             
#>  bindr         0.1.1      2018-03-13 CRAN (R 3.4.4)                    
#>  bindrcpp    * 0.2.2      2018-03-29 CRAN (R 3.4.4)                    
#>  colorspace    1.3-2      2016-12-14 CRAN (R 3.4.0)                    
#>  compiler      3.4.3      2017-12-07 local                             
#>  datasets    * 3.4.3      2017-12-07 local                             
#>  devtools      1.13.5     2018-02-18 CRAN (R 3.4.3)                    
#>  digest        0.6.15     2018-01-28 CRAN (R 3.4.3)                    
#>  dplyr         0.7.4      2017-09-28 CRAN (R 3.4.2)                    
#>  evaluate      0.10.1     2017-06-24 cran (@0.10.1)                    
#>  gghighlight * 0.0.1      2017-10-05 CRAN (R 3.4.2)                    
#>  ggplot2       2.2.1.9000 2018-03-31 Github (tidyverse/ggplot2@3c9c504)
#>  glue          1.2.0      2017-10-29 CRAN (R 3.4.2)                    
#>  graphics    * 3.4.3      2017-12-07 local                             
#>  grDevices   * 3.4.3      2017-12-07 local                             
#>  grid          3.4.3      2017-12-07 local                             
#>  gtable        0.2.0      2016-02-26 CRAN (R 3.4.0)                    
#>  htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                    
#>  knitr         1.20       2018-02-20 CRAN (R 3.4.3)                    
#>  lazyeval      0.2.1      2017-10-29 CRAN (R 3.4.2)                    
#>  magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                    
#>  memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                    
#>  methods     * 3.4.3      2017-12-07 local                             
#>  munsell       0.4.3      2016-02-13 CRAN (R 3.4.0)                    
#>  pillar        1.2.1      2018-02-27 CRAN (R 3.4.3)                    
#>  pkgconfig     2.0.1      2017-03-21 CRAN (R 3.4.0)                    
#>  plyr          1.8.4      2016-06-08 CRAN (R 3.4.0)                    
#>  purrr         0.2.4      2017-10-18 CRAN (R 3.4.2)                    
#>  R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                    
#>  Rcpp          0.12.16    2018-03-13 CRAN (R 3.4.4)                    
#>  rlang         0.2.0.9001 2018-04-01 Github (r-lib/rlang@49d7a34)      
#>  rmarkdown     1.9        2018-03-01 CRAN (R 3.4.3)                    
#>  rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.3)                    
#>  scales        0.5.0.9000 2018-03-31 Github (hadley/scales@d767915)    
#>  stats       * 3.4.3      2017-12-07 local                             
#>  stringi       1.1.7      2018-03-12 CRAN (R 3.4.4)                    
#>  stringr       1.3.0      2018-02-19 CRAN (R 3.4.3)                    
#>  tibble        1.4.2      2018-01-22 CRAN (R 3.4.3)                    
#>  tools         3.4.3      2017-12-07 local                             
#>  utils       * 3.4.3      2017-12-07 local                             
#>  withr         2.1.2      2018-04-01 Github (jimhester/withr@79d7b0d)  
#>  yaml          2.1.18     2018-03-08 CRAN (R 3.4.4)
```

</details>

**Comment by yutannihilation** [comment] 2018-04-02 01:12
Thanks, confirmed. It seems gghighlight won't work with the dev version of ggplot2 (the CRAN version is OK, though).

**Comment by yutannihilation** [comment] 2018-04-02 01:16
Since I'm planning to overhaul the package by using some new feature which will be included in the next release of ggplot2, this issue won't be addressed until the new API will be stable. If you do need to use this package, please use the CRAN version of ggplot2.

**Comment by yutannihilation** [comment] 2018-06-02 04:43
I think this should work now!

FYI, the following is the new equivalent to `gghighlight_line(d, aes(idx, value, colour = type), max(value) > 20)` (I might rename `geom_highlight()`, though):

```r
ggplot(d, aes(idx, value, colour = type)) +
  geom_line() +
  geom_highlight(max(value) > 20)
```

**Closed by yutannihilation** 2018-06-02 04:43 UTC
Labels: bug
