### ISSUE TITLE
More control of colors of the 'highlighted' lines

### ISSUE THREAD

**Issue by liao961120** [yutannihilation/gghighlight#82] opened 2019-01-04 04:33 UTC
Is is possible to control the colors of highlighted lines?

In the example below, I highlighted the line 'envelope'. Before highlighting, the line is blue; after highlighting it with `gghighlight()`, it changes to red.

I would like to know if it's possible to retain the original colors of the lines after highlighting them with `gghighlight()`?

``` r
library(ggplot2)
library(gghighlight)
library(dplyr)

fp <- url('https://raw.githubusercontent.com/liao961120/local_depend/master/107-1/socpsy_plot/poplev-helping2.csv')

poplev_helping <- readr::read_csv(fp) %>% 
  tidyr::gather("types", "y", -pop_level)

poplev_helping[seq(from=1, to=15, by=3),]
```

    ## # A tibble: 5 x 3
    ##   pop_level types               y
    ##       <int> <chr>           <dbl>
    ## 1         1 answer question  81.2
    ## 2         4 answer question  71.5
    ## 3         2 dontation        40  
    ## 4         5 dontation         8  
    ## 5         3 envelope          5.7

``` r
p <- ggplot(poplev_helping,
            aes(x = pop_level, color = types)) +
  geom_line(aes(y = y))
p
```

![](https://raw.githubusercontent.com/liao961120/local_depend/master/107-1/socpsy_plot/gghighlight-issue_files/figure-markdown_github/unnamed-chunk-1-1.png)

``` r
p + gghighlight(types %in% c('donation', 'envelope'))
```

    ## Warning: Tried to calculate with group_by(), but the calculation failed.
    ## Falling back to ungrouped filter operation...

    ## label_key: types

![](https://raw.githubusercontent.com/liao961120/local_depend/master/107-1/socpsy_plot/gghighlight-issue_files/figure-markdown_github/unnamed-chunk-1-2.png)

Thanks for this cool package.

**Comment by yutannihilation** [comment] 2019-01-04 04:59
Thanks, I'm closing this issue for now since this seems a duplicate of #72.

I'm still thinking if this is possible. One solution is to use factor and specify `drop = FALSE` in the scale, but I'm not sure if this really fits in gghighlight...

``` r
library(ggplot2)
library(gghighlight)
library(dplyr, warn.conflicts = FALSE)

fp <- url('https://raw.githubusercontent.com/liao961120/local_depend/master/107-1/socpsy_plot/poplev-helping2.csv')

poplev_helping <- readr::read_csv(fp) %>% 
  tidyr::gather("types", "y", -pop_level)
#> Parsed with column specification:
#> cols(
#>   pop_level = col_double(),
#>   `answer question` = col_double(),
#>   dontation = col_double(),
#>   envelope = col_double()
#> )

# convert characters to factors in order to preserve the levels
poplev_helping_fct <- poplev_helping %>%
  mutate_if(is.character, factor)

p <- ggplot(poplev_helping_fct,
       aes(x = pop_level, color = types)) +
  geom_line(aes(y = y)) +
  gghighlight(types %in% c('donation', 'envelope'), use_direct_label = FALSE)
#> Warning: Tried to calculate with group_by(), but the calculation failed.
#> Falling back to ungrouped filter operation...

library(patchwork)

p * (p + scale_colour_discrete(drop = FALSE))
```

![](https://i.imgur.com/NRDdaGz.png)

<sup>Created on 2019-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Closed by yutannihilation** 2019-01-04 04:59 UTC

**Comment by liao961120** [comment] 2019-01-04 08:30
I'm sorry for the duplication. Thank you for the clear reply!

**Comment by yutannihilation** [comment] 2019-03-09 13:28
@liao961120 The dev version of gghighlight now has `keep_scale` argument.

``` r
library(ggplot2)
library(gghighlight)
library(dplyr, warn.conflicts = FALSE)
library(patchwork)

fp <- url('https://raw.githubusercontent.com/liao961120/local_depend/master/107-1/socpsy_plot/poplev-helping2.csv')

poplev_helping <- readr::read_csv(fp) %>% 
  tidyr::gather("types", "y", -pop_level)
#> Parsed with column specification:
#> cols(
#>   pop_level = col_double(),
#>   `answer question` = col_double(),
#>   dontation = col_double(),
#>   envelope = col_double()
#> )

p1 <- ggplot(poplev_helping,
            aes(x = pop_level, color = types)) +
  geom_line(aes(y = y))

p2 <- p1 + gghighlight(types %in% c('donation', 'envelope'), keep_scale = TRUE)
#> Warning: Tried to calculate with group_by(), but the calculation failed.
#> Falling back to ungrouped filter operation...
#> label_key: types

p1 * p2
```

![](https://i.imgur.com/KxSNkpe.png)

<sup>Created on 2019-03-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by liao961120** [comment] 2019-03-11 06:44
Fantastic!!! Thank you so much~  
It' ll save me a lot of manual work.
