### ISSUE TITLE
Error: `:=` can only be used within a quasiquoted argument

### ISSUE THREAD

**Issue by floraliu1011** [yutannihilation/gghighlight#64] opened 2018-08-02 14:35 UTC
Hi I was trying to follow your examples to highlight my boxplot in ggplot it just didn't work.
Here is my code:
```
> P2 = ggplot(plotdf) +                                       
+     geom_boxplot(aes(x = N, y = Evalue, colour = pepSeq)) + 
+     scale_y_log10() +                                       
+     theme(legend.position = "None") +                       
+     gghighlight(Evalue < 0.0001, label_key = pepSeq)        
Error: `:=` can only be used within a quasiquoted argument    
```
I ran ls() and there is no other variables named Evalue

Could you please help me with where I'm wrong?

**Comment by yutannihilation** [comment] 2018-08-03 01:09
Thanks for reporting. From the message, the error seems to occur here:

https://github.com/yutannihilation/gghighlight/blob/67284d7752a226e5e23bd239993616cd26720e85/R/gghighlight.R#L311

But, so far I can't reproduce this error on my laptop... Could you try providing a [reprex](https://reprex.tidyverse.org/index.html)?

**Comment by yutannihilation** [comment] 2018-08-03 01:14
Updating rlang (or dplyr?) package might solve the issue, if you are using the older version.

**Comment by yutannihilation** [comment] 2018-10-12 03:59
@floraliu1011 I'm closing this for now as I can't reproduce the error. Please feel free to reopen if you provide a [reprex](https://reprex.tidyverse.org/index.html) for this.

**Closed by yutannihilation** 2018-10-12 03:59 UTC
